

wtb:
  redis:
    pool:
      max-total: 1000
      min-idle: 20
      
    single: 
      url : redis://localhost:6379/
#      url : redis://:GnUNkSzxMy0zbPH0@r-bp16e7dbe47100e4.redis.rds.aliyuncs.com:6379/

    shard:
      urls:
#        - redis://:soy4xVhAWW1kVXYS@172.16.15.125@6379/
#        - redis://:soy4xVhAWW1kVXYS@172.16.15.125@7379/
#        - redis://:soy4xVhAWW1kVXYS@172.16.15.125@8379/
#        - redis://:soy4xVhAWW1kVXYS@172.16.15.125@9379/
#        - redis://:soy4xVhAWW1kVXYS@172.16.15.125@9380/
#        - redis://:soy4xVhAWW1kVXYS@172.16.15.125@9381/
#        - redis://:soy4xVhAWW1kVXYS@172.16.15.125@9382/
#        - redis://:soy4xVhAWW1kVXYS@172.16.15.125@9383/
        - redis://localhost:6379/
        - redis://localhost:7379/
        - redis://localhost:8379/
        
  test:
    number: 5_000_000
    concurrency: 20
    value-size: 2_0
    summary-step: 100_000

