
wtb:
  redis:
    pool:
      max-total: 1000
      min-idle: 20
      
      
    single: 
#      url : redis://localhost:88/
#      url : redis://localhost:6379
      url: redis://:Mt9bJb6hyLjwYinh~@192.168.100.112:8635
      
#      url : redis://:GnUNkSzxMy0zbPH0@r-bp124a31fc2890a4.redis.rds.aliyuncs.com:6379/

#    shard:
#      urls:
#        - redis://localhost:6379/
#        - redis://localhost:7379/
#        - redis://localhost:8379/
        
  test:
    number: 400_000
    concurrency: 10
    range-size: 100
    value-size: 1_000
    summary-step: 100_000
 #   summary-speed-step: 200_000
    print-percents: >
      .5, .75, .8, .9,
      .91, .92, .93, .94, .95, .96, .97, .98, .99, 
      .991, .992, .993, .994, .995, .996, .997, .998, .999, 
      .9991, .9992, .9993, .9993, .9994, .9995, .9996, .9997, .9998, .9999, 
      .99991, .99992, .99993, .99993, .99994, .99995, .99996, .99997, .99998, .99999, 
      1

